version: '3.5'
services:
  backend-app:
    build: .
    container_name: backend
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/data/postgres
    ports:
      - 5432:5432
volumes:
  db: