version: '3.5'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: typeorm
    healthcheck:
      test: ["CMD-SHELL", "ps_isseady"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/data/postgres
    ports:
      - 5432:5432
volumes:
  db: